// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrl5sTQDscMRcJ1Yx0izTRW7thXDNAyHY',
    appId: '1:1036672191814:android:68dec1ad5d2a8d951a2947',
    messagingSenderId: '1036672191814',
    projectId: 'appn-b8de2',
    storageBucket: 'appn-b8de2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkDZju8-LMrgGTOGan8gjwmiMCL_agL9c',
    appId: '1:1036672191814:ios:e1b36da5fa93d7221a2947',
    messagingSenderId: '1036672191814',
    projectId: 'appn-b8de2',
    storageBucket: 'appn-b8de2.appspot.com',
    androidClientId: '1036672191814-4d3ct5je967hv5a562i1b4c7a0o31ave.apps.googleusercontent.com',
    iosClientId: '1036672191814-2jdsgnbd1duk7js0cfura37iv6tghf97.apps.googleusercontent.com',
    iosBundleId: 'com.example.napp',
  );
}
